# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: is_spinnaker_gateway/conf/options.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='is_spinnaker_gateway/conf/options.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'is_spinnaker_gateway/conf/options.proto\"\xf0\x01\n\x06\x43\x61mera\x12\n\n\x02id\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12,\n\talgorithm\x18\x03 \x01(\x0e\x32\x19.ColorProcessingAlgorithm\x12 \n\x18onboard_color_processing\x18\x04 \x01(\x08\x12\x15\n\ruse_turbojpeg\x18\x05 \x01(\x08\x12\x13\n\x0bpacket_size\x18\x06 \x01(\x05\x12\x14\n\x0cpacket_delay\x18\x07 \x01(\x05\x12\x11\n\treverse_x\x18\x08 \x01(\x08\x12\x11\n\treverse_y\x18\t \x01(\x08\x12\x16\n\x0einitial_config\x18\n \x01(\t\"Y\n\x14\x43\x61meraGatewayOptions\x12\x14\n\x0crabbitmq_uri\x18\x01 \x01(\t\x12\x12\n\nzipkin_uri\x18\x02 \x01(\t\x12\x17\n\x06\x63\x61mera\x18\x03 \x01(\x0b\x32\x07.Camera*\xe0\x01\n\x18\x43olorProcessingAlgorithm\x12\x11\n\rNOT_SPECIFIED\x10\x00\x12\x14\n\x10NEAREST_NEIGHBOR\x10\x01\x12\x1c\n\x18NEAREST_NEIGHBOR_AVERAGE\x10\x02\x12\x10\n\x0c\x45\x44GE_SENSING\x10\x03\x12\r\n\tHQ_LINEAR\x10\x04\x12\x0c\n\x08\x42ILINEAR\x10\x05\x12\x16\n\x12\x44IRECTIONAL_FILTER\x10\x06\x12\x1f\n\x1bWEIGHTED_DIRECTIONAL_FILTER\x10\x07\x12\x0c\n\x08RIGOROUS\x10\x08\x12\x07\n\x03IPP\x10\tb\x06proto3'
)

_COLORPROCESSINGALGORITHM = _descriptor.EnumDescriptor(
  name='ColorProcessingAlgorithm',
  full_name='ColorProcessingAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_SPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEAREST_NEIGHBOR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEAREST_NEIGHBOR_AVERAGE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EDGE_SENSING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HQ_LINEAR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BILINEAR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIRECTIONAL_FILTER', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEIGHTED_DIRECTIONAL_FILTER', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGOROUS', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IPP', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=378,
  serialized_end=602,
)
_sym_db.RegisterEnumDescriptor(_COLORPROCESSINGALGORITHM)

ColorProcessingAlgorithm = enum_type_wrapper.EnumTypeWrapper(_COLORPROCESSINGALGORITHM)
NOT_SPECIFIED = 0
NEAREST_NEIGHBOR = 1
NEAREST_NEIGHBOR_AVERAGE = 2
EDGE_SENSING = 3
HQ_LINEAR = 4
BILINEAR = 5
DIRECTIONAL_FILTER = 6
WEIGHTED_DIRECTIONAL_FILTER = 7
RIGOROUS = 8
IPP = 9



_CAMERA = _descriptor.Descriptor(
  name='Camera',
  full_name='Camera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Camera.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Camera.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='Camera.algorithm', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='onboard_color_processing', full_name='Camera.onboard_color_processing', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_turbojpeg', full_name='Camera.use_turbojpeg', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_size', full_name='Camera.packet_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_delay', full_name='Camera.packet_delay', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reverse_x', full_name='Camera.reverse_x', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reverse_y', full_name='Camera.reverse_y', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial_config', full_name='Camera.initial_config', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=284,
)


_CAMERAGATEWAYOPTIONS = _descriptor.Descriptor(
  name='CameraGatewayOptions',
  full_name='CameraGatewayOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rabbitmq_uri', full_name='CameraGatewayOptions.rabbitmq_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zipkin_uri', full_name='CameraGatewayOptions.zipkin_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera', full_name='CameraGatewayOptions.camera', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=375,
)

_CAMERA.fields_by_name['algorithm'].enum_type = _COLORPROCESSINGALGORITHM
_CAMERAGATEWAYOPTIONS.fields_by_name['camera'].message_type = _CAMERA
DESCRIPTOR.message_types_by_name['Camera'] = _CAMERA
DESCRIPTOR.message_types_by_name['CameraGatewayOptions'] = _CAMERAGATEWAYOPTIONS
DESCRIPTOR.enum_types_by_name['ColorProcessingAlgorithm'] = _COLORPROCESSINGALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Camera = _reflection.GeneratedProtocolMessageType('Camera', (_message.Message,), {
  'DESCRIPTOR' : _CAMERA,
  '__module__' : 'is_spinnaker_gateway.conf.options_pb2'
  # @@protoc_insertion_point(class_scope:Camera)
  })
_sym_db.RegisterMessage(Camera)

CameraGatewayOptions = _reflection.GeneratedProtocolMessageType('CameraGatewayOptions', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAGATEWAYOPTIONS,
  '__module__' : 'is_spinnaker_gateway.conf.options_pb2'
  # @@protoc_insertion_point(class_scope:CameraGatewayOptions)
  })
_sym_db.RegisterMessage(CameraGatewayOptions)


# @@protoc_insertion_point(module_scope)
